name: Salesforce CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v5 # ← Actualizado de v3 a v5

      - name: Instalar Node.js
        uses: actions/setup-node@v5 # ← Actualizado de v4 a v5
        with:
          node-version: "20"

      - name: Instalar Salesforce CLI
        run: |
          npm install @salesforce/cli --location=global
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      - name: Verificar instalación
        run: sf --version

      - name: Autenticarse con Dev Hub
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth.txt
          sf org login sfdx-url -f auth.txt -a devhub -d

      - name: Deploy a la org
        run: sf project deploy start --source-dir force-app --target-org devhub --wait 10
